apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: falco
  namespace: argocd
spec:
  project: default
  sources:
  - chart: falco
    repoURL: https://falcosecurity.github.io/charts
    targetRevision: override-me
    helm:
      releaseName: falco
      valueFiles:
      - $values/override-me.yaml
  - repoURL: 'https://github.com/edwinvandeven/k8s-playground.git'
    targetRevision: main
    ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: falco
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
