  resources:
  - ../../base/strimzi

  patches:
  - path: patches/patch-targetRevision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: strimzi-operator
  - path: patches/patch-valuesPath.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: strimzi-operator
