apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: opencost
  namespace: argocd
spec:
  project: default
  source:
    chart: opencost
    repoURL: https://opencost.github.io/opencost-helm-chart
    targetRevision: override-me
    helm:
      releaseName: opencost
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
