opencost:
  prometheus:
    internal:
      # -- Use in-cluster Prometheus
      enabled: true
      # -- Service name of in-cluster Prometheus
      serviceName: kube-prometheus-stack-prometheus
      # -- Namespace of in-cluster Prometheus
      namespaceName: monitoring
      # -- Service port of in-cluster Prometheus
      port: 9090
      # -- Scheme to use for in-cluster Prometheus
      scheme: http
  customPricing:
    enabled: true
    costModel:
      description: Modified prices based on your internal pricing
      CPU: 1.25
      RAM: 0.50
      storage: 0.25
      