apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kubecost
  namespace: argocd
spec:
  project: default
  sources:
    - chart: cost-analyzer
      repoURL: https://kubecost.github.io/cost-analyzer/
      targetRevision: override-me
      helm:
        releaseName: kubecost
        valueFiles:
          - $values/override-me.yaml
    - repoURL: "https://github.com/edwinvandeven/k8s-playground.git"
      targetRevision: main
      ref: values
  destination:
    server: "https://kubernetes.default.svc"
    namespace: kubecost
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
