defaultRules:
  create: true
alertmanager:
  enabled: false
prometheus:
  enabled: true
  promtheusSpec:
    retention: 1d
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
grafana:
  # This should be changed for prd to be read from a secret.
  adminPassword: hello-world

# # values_minikube.yaml
# coreDns:
#   service:
#     selector:
#       k8s-app: kube-dns
# kubeControllerManager:
#   service:
#     selector:
#       k8s-app: null
#       component: kube-controller-manager
# kubeEtcd:
#   service:
#     selector:
#       k8s-app: null
#       component: etcd
# kubeScheduler:
#   service:
#     selector:
#       k8s-app: null
#       component: kube-scheduler