defaultRules:
  create: true
alertmanager:
  enabled: false
prometheus:
  enabled: true
  promtheusSpec:
    retention: 1d
    podMonitorSelectorNilUsesHelmValues: false
    serviceMonitorSelectorNilUsesHelmValues: false
grafana:
  # This should be changed for prd to be read from a secret.
  adminPassword: hello-world
