  resources:
  - ../../base/sealed-secrets

  patches:
  - path: patches/patch-targetRevision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: sealed-secrets
      # namespace: argocd