  resources:
  - ../../base/vault

  patches:
  # MySQL
  - path: patches/patch-targetRevision-mysql.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: mysql
  - path: patches/patch-valuesPath-mysql.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: mysql
  # MySQL
  - path: patches/patch-targetRevision-vault.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
  - path: patches/patch-valuesPath-vault.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: vault
