  resources:
  - ../../base/metrics-server

  patches:
  - path: patches/patch-targetRevision.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: metrics-server
  - path: patches/patch-valuesPath.yaml
    target:
      group: argoproj.io
      version: v1alpha1
      kind: Application
      name: metrics-server